scripts/qemu-guest: Warn without TTY
The current `socat` setup requires that `qemu-guest` runs
on a (pseudo) TTY. If this is not the case, an error
messages is printed.

Signed-off-by: Simon Kuenzer <simon.kuenzer@neclab.eu>

diff --git a/scripts/qemu-guest b/scripts/qemu-guest
--- a/scripts/qemu-guest
+++ b/scripts/qemu-guest
@@ -702,6 +702,13 @@ EOF
 done
 shift $(( OPTIND - 1 ))
 
+# Sanity check: TTY availble? socat will need it
+if [ $OPT_BACKGROUND -ne 0 ]; then
+	if [ ! -t 0 -o ! -t 1 ]; then
+		echo "A TTY is required for foreground mode (see option -x)" 1>&2
+		exit 2
+	fi
+fi
 
 case "$ARG_MACHINETYPE" in
 	"arm64v")
